name: introvertdiaries
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

#router
  auto_route: ^8.1.3

  #google fonts
  google_fonts: ^6.2.1

  #dependency injection
  get_it: ^7.2.0
  injectable: ^2.1.0

  #state management
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.1.2

  #path_provider
  path_provider: ^2.1.1

  #data models
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  equatable: ^2.0.5

  #functional programmings
  dartz: ^0.10.1

  #network connectivity
  internet_connection_checker: ^1.0.0+1

  #network requests
  dio: ^5.3.1

  #env
  flutter_dotenv: ^5.0.2

  #Session
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0

  #logger
  logging: ^1.1.0

  #device_info
  device_info_plus: ^10.1.0

  #native splash
  # flutter_native_splash: ^2.2.16

  #image and svg renderer
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  super_rich_text: ^1.0.0
  flutter_animate: ^4.2.0+1
  flutter_hooks: ^0.20.0

  #dropdown
  dropdown_button2: ^2.3.7

  #bottom_sheet
  modal_bottom_sheet: ^3.0.0

  # crash analytics
  sentry_flutter: ^8.2.0

  #user input
  pinput: ^4.0.0

  #datepicker
  # syncfusion_flutter_datepicker: ^22.2.9

  # devicelocale
  devicelocale: ^0.7.1

  # scroll to index
  scrollable_positioned_list: ^0.3.8

  #  inview_notifier_list
  inview_notifier_list: ^3.0.0

  #exapandableText
  expandable_text: ^2.3.0
  # logger
  pretty_dio_logger: ^1.3.1

  #chat bubbtles
  chat_bubbles: ^1.6.0

  #sms autofill
  sms_autofill: ^2.3.0

  #file_picker
  file_picker: ^8.0.3

  #permission handler
  permission_handler: ^11.3.1

  #shimmer effect
  shimmer: ^3.0.0

  # date time
  jiffy: ^6.2.1

  # share
  share_plus: ^9.0.0

  # images
  image_picker: ^1.0.4

  #video playing
  chewie: ^1.7.1

  #jwtdecoder
  jwt_decoder: ^2.0.1

  #video thumbnail maker
  hooks_riverpod: ^2.4.3

  flutter_animated_button: ^2.0.3
  uuid: ^4.4.0

  dart_jsonwebtoken: ^2.12.0
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.2.1
  lottie: ^3.1.1

  package_info_plus: ^8.0.0
  map_launcher: ^3.0.1
  rxdart: ^0.27.7

  carousel_slider: ^4.2.1
  in_app_update: ^4.2.3
  flutter_rating_bar: ^4.0.1

  # notification
  awesome_notifications: ^0.9.3+1

  # dialog
  animations: ^2.0.11

  # in app review
  in_app_review: ^2.0.8
  flutter_facebook_auth: ^6.0.3
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^6.1.0
  firebase_analytics: ^10.7.1
  firebase_messaging: ^14.7.5
  firebase_core: ^2.23.0

  #image_cropper
  image_cropper: ^5.0.1
  # photo_manager: ^2.8.1

  dio_smart_retry: ^6.0.0
  socket_io_client: ^2.0.3+1
  flutter_fast_cli: ^1.4.9
  flutter_custom_clippers: ^2.1.0
  firebase_remote_config: ^4.3.13
  shared_preferences: ^2.2.2
  auto_size_text: ^3.0.0
  simple_progress_indicators: ^0.2.0
  flutter_html: ^3.0.0-beta.2
  upgrader: ^10.3.0
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  #generators
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  freezed: ^2.3.2
  injectable_generator: ^2.1.3
  hive_generator: ^2.0.0
  auto_route_generator: ^8.0.0

  # launcher icons
  flutter_launcher_icons:
    git:
      url: https://github.com/Davenchy/flutter_launcher_icons.git
      ref: fixMinSdkParseFlutter2.8
  flutter_gen_runner: ^5.3.1
  very_good_analysis: ^5.0.0+1

  

flutter:
  uses-material-design: true

  assets:
    - assets/country_info.json

